In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_digits
import warnings
from sklearn.ensemble import RandomForestClassifier
warnings.filterwarnings('ignore')

In [6]:
df=load_digits()

In [8]:
x=df.data
y= df.target

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [11]:
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\Users\00824732\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9611111111111111

In [12]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [13]:
for train_index,test_index in kf.split([1,2,3,4,5]):
    print(train_index,test_index)

[2 3 4] [0 1]
[0 1 4] [2 3]
[0 1 2 3] [4]


In [15]:
def get_score(model,x_train,x_test,y_train,y_test):
        model.fit(x_train,y_train)
        return model.score(x_test,y_test)

In [16]:
get_score(SVC(),x_train,x_test,y_train,y_test)

0.9851851851851852

In [20]:
scores_l=[]
scores_svm=[]
scores_rf=[]
for train_index,test_index in kf.split(df.data):
    x_train,y_train,x_test,y_test=df.data[train_index],df.data[test_index],\
        df.target[train_index],df[test_index]
    scores_l.append(get_score(LogisticRegression(),x_train,y_train,x_test,y_test))
    scores_svc.append(get_score(SVC(),x_train,y_train,x_test,y_test))

TypeError: unhashable type: 'numpy.ndarray'

In [21]:
from sklearn.model_selection import cross_val_score

In [24]:
cross_val_score(LogisticRegression(),df.data,df.target)

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [26]:
    cross_val_score(SVC(),df.data,df.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [29]:
    cross_val_score(RandomForestClassifier(n_estimators=40),df.data,df.target)

array([0.93055556, 0.90277778, 0.95543175, 0.95264624, 0.91643454])